### ISSUE TITLE
PS Time series - change font and color

### ISSUE THREAD

**Issue by alexbruy** [faunalia/ps-speed#2]
When "change font and color" button is pressed occours this error:

```
Traceback (most recent call last):
File "C:/Users/lucalant/.qgis2/python/plugins\pstimeseries\pstimeseries_dlg.py", line 451, in openFontColorSettings
dlg = GraphSettings_Dlg(self)
File "C:/Users/lucalant/.qgis2/python/plugins\pstimeseries\graph_settings_dialog.py", line 46, in init
props = self.findFont( {'family':family} )
File "C:/Users/lucalant/.qgis2/python/plugins\pstimeseries\graph_settings_dialog.py", line 295, in findFont
font = FontProperties( fname=findfont( FontProperties(**props) ) )
File "C:\PROGRA~1\QGISCH~1\apps\Python27\lib\site-packages\matplotlib\font_manager.py", line 682, in init
self.set_fontconfig_pattern(family)
File "C:\PROGRA~1\QGISCH~1\apps\Python27\lib\site-packages\matplotlib\font_manager.py", line 910, in set_fontconfig_pattern
for key, val in self._parse_fontconfig_pattern(pattern).iteritems():
File "C:\PROGRA~1\QGISCH~1\apps\Python27\lib\site-packages\matplotlib\font_manager.py", line 694, in _parse_fontconfig_pattern
return parse_fontconfig_pattern(pattern)
File "C:\PROGRA~1\QGISCH~1\apps\Python27\lib\site-packages\matplotlib\fontconfig_pattern.py", line 129, in parse
"Could not parse font string: '%s'\n%s" % (pattern, e))
ValueError: Could not parse font string: 'SimSun-ExtB'
Expected end of text (at char 6), (line:1, col:7)
```

**Comment by ghtmtt** [comment]
fixed in 7bc6a6a60e90e8ace2ccf54183af8119fb357945
